AWSTemplateFormatVersion: 2010-09-09
Description: >-
  readapp-backend-volumes

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  GetVolumeByIdFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: GetVolumeByIdFunction
      Handler: handlers/volumes/get-by-id.getByIdHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: Retrieve a single volume via Google Books API.

  GetAllVolumesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: GetAllVolumesFunction
      Handler: handlers/volumes/get-all.getAllHandler
      Runtime: nodejs14.x
      MemorySize: 256
      Timeout: 100
      Description: Retrieve a list of volumes filtered using the input query via Google Books API.

  GetAllVolumeCategoriesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: GetAllVolumeCategoriesFunction
      Handler: handlers/categories/get-all.getAllHandler
      Runtime: nodejs14.x
      MemorySize: 256
      Timeout: 100
      Description: Retrieve a list of volume categories filtered by locale via Google Books API.

  GetVolumesInCategoryFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: GetVolumesInCategoryFunction
      Handler: handlers/categories/get-volumes.handler
      Runtime: nodejs14.x
      MemorySize: 256
      Timeout: 100
      Description: Retrieve a list of volumes associated to a specific category via Google Books API.

Outputs:
  LambdaExportGetVolumeByIdFunction:
    Description: Lambda function getVolumeByIdFunction
    Value: !Ref GetVolumeByIdFunction
    Export:
      Name: ReadAppGetVolumeByIdFunction

  LambdaExportGetAllVolumesFunction:
    Description: Lambda function getAllVolumesFunction
    Value: !Ref GetAllVolumesFunction
    Export:
      Name: ReadAppGetAllVolumesFunction

  LambdaExportGetAllVolumeCategoriesFunction:
    Description: Lambda function getAllVolumeCategoriesFunction
    Value: !Ref GetAllVolumeCategoriesFunction
    Export:
      Name: ReadAppGetAllVolumeCategoriesFunction

  LambdaExportGetVolumesInCategoryFunction:
    Description: Lambda function getVolumesInCategoryFunction
    Value: !Ref GetVolumesInCategoryFunction
    Export:
      Name: ReadAppGetVolumesInCategoryFunction